services:
  - type: web
    name: assistantbiblique
    runtime: python
    plan: free
    buildCommand: ./build.sh
    startCommand: python main.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
    buildFilter:
      paths:
        - requirements.txt
        - build.sh
        - main.py
    autoDeploy: true
